image:
  file: .gitpod.Dockerfile

tasks:
  - init: |

      go get && go build ./...
  - command: |
      goose -dir migrations sqlite3 /litefs/potato.db up
      go run scripts/seed.go

vscode:
  extensions:
    - qwtel.sqlite-viewer
    - golang.go
    - redhat.vscode-yaml
