version: "3"

tasks:
  dev:
    deps: [devcss, air]

  build:
    deps: [buildcss, sqlc, buildmain]

  buildmain:
    cmds:
      - templ generate && go build -o ./tmp/main ./cmd/main.go

  test:
    cmds:
      - go test -v ./...

  # hot reload
  air:
    cmds:
      - air

  buildcss:
    cmds:
      - tailwindcss -i ./styles/input.css -o ./static/css/styles.css --minify

  devcss:
    cmds:
      - tailwindcss -i ./styles/input.css -o ./static/css/styles.css --watch

  # reset local
  reset:
    cmds:
      - rm /litefs/potato.db
      - goose -dir migrations sqlite3 /litefs/potato.db up
      - task: seed

  seed:
    cmds:
      - go run scripts/seed.go

  sqlc:
    cmds:
      - sqlc generate

  lint:
    cmds:
      - staticcheck cmd/main.go

  migrate:
    cmds:
      - goose -dir migrations sqlite3 /litefs/potato.db up

  docker-build:
    cmds:
      - DOCKER_BUILDKIT=1 docker build -t latest .

  docker-run:
    cmds:
      - docker run -p 8080:8080 -it --rm --device /dev/fuse --cap-add SYS_ADMIN latest
