version: "3"

tasks:
  dev:
    deps: [css, air]

  # hot reload
  air:
    cmds:
      - air

  buildcss:
    cmds:
      - tailwindcss -i ./styles/input.css -o ./static/styles.css --minify

  css:
    cmds:
      - tailwindcss -i ./styles/input.css -o ./static/styles.css --watch

  # css + other assets
  assets:
    deps: [css]

  # these are old ones here, using scss and things
  sass:
    cmds:
      - sass -w styles/input.scss tempcss/output.css

  postcss:
    cmds:
      - npx postcss tempcss/output.css -o static/styles.css -m -w

  # reset local
  reset:
    cmds:
      - rm /litefs/potato.db
      - goose -dir migrations sqlite3 /litefs/potato.db up
      - task: seed

  seed:
    cmds:
      - go run scripts/seed.go

  sqlc:
    cmds:
      - sqlc generate

  lint:
    cmds:
      - staticcheck cmd/main.go

  migrate:
    cmds:
      - goose -dir migrations sqlite3 /litefs/potato.db up
