version: "3"

tasks:
  dev:
    deps: [css, air]

  # hot reload
  air:
    cmds:
      - air

  buildcss:
    cmds:
      - postcss styles/input.css -o static/styles.css -m 

  css:
    cmds:
      - npx postcss styles/input.css -o static/styles.css -m 

 
  # reset local
  reset:
    cmds:
      - rm /litefs/potato.db
      - goose -dir migrations sqlite3 /litefs/potato.db up
      - task: seed

  seed:
    cmds:
      - go run scripts/seed.go

  sqlc:
    cmds:
      - sqlc generate

  lint:
    cmds:
      - staticcheck cmd/main.go

  migrate:
    cmds:
      - goose -dir migrations sqlite3 /litefs/potato.db up
