version: "3"

tasks:
  dev:
    deps: [assets, air]

  # hot reload
  air:
    cmds:
      - air

  # css + other assets
  assets:
    deps: [sass, postcss]

  sass:
    cmds:
      - sass -w styles/input.scss styles/output.css

  postcss:
    cmds:
      - npx postcss styles/output.css -o static/styles.css -m -w

  # reset local
  reset:
    cmds:
      - rm /litefs/potato.db
      - goose -dir migrations sqlite3 /litefs/potato.db up
      - task: seed

  seed:
    cmds:
      - go run scripts/seed.go

  sqlc:
    cmds:
      - sqlc generate

  lint:
    cmds:
      - staticcheck cmd/main.go

  migrate:
    cmds:
      - goose -dir migrations sqlite3 /litefs/potato.db up
