// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// This is a base page template. All the other template pages implement this interface.
//

//line views/base.qtpl:3
package views

//line views/base.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/base.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/base.qtpl:4
type Page interface {
//line views/base.qtpl:4
	Title() string
//line views/base.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
//line views/base.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
//line views/base.qtpl:4
	Body() string
//line views/base.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
//line views/base.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line views/base.qtpl:4
}

// Page prints a page implementing Page interface.

//line views/base.qtpl:12
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line views/base.qtpl:12
	qw422016.N().S(`
<!DOCTYPE html>
	 <html>
	 	<head>
 	<script src="https://cdn.jsdelivr.net/npm/@unocss/runtime/uno.global.js"></script>
	 		<meta charset="UTF-8">
	 		<title>`)
//line views/base.qtpl:18
	p.StreamTitle(qw422016)
//line views/base.qtpl:18
	qw422016.N().S(`</title>
	 	</head>
	 	<body>
	 `)
//line views/base.qtpl:21
	p.StreamBody(qw422016)
//line views/base.qtpl:21
	qw422016.N().S(`
	 	</body>
	 </html>
<html>
`)
//line views/base.qtpl:25
}

//line views/base.qtpl:25
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line views/base.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/base.qtpl:25
	StreamPageTemplate(qw422016, p)
//line views/base.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line views/base.qtpl:25
}

//line views/base.qtpl:25
func PageTemplate(p Page) string {
//line views/base.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line views/base.qtpl:25
	WritePageTemplate(qb422016, p)
//line views/base.qtpl:25
	qs422016 := string(qb422016.B)
//line views/base.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line views/base.qtpl:25
	return qs422016
//line views/base.qtpl:25
}

// Base page implementation. Other pages may inherit from it if they need
// overriding only certain Page methods

//line views/base.qtpl:30
type BasePage struct{}

//line views/base.qtpl:31
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line views/base.qtpl:31
	qw422016.N().S(`This is a base title`)
//line views/base.qtpl:31
}

//line views/base.qtpl:31
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line views/base.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/base.qtpl:31
	p.StreamTitle(qw422016)
//line views/base.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line views/base.qtpl:31
}

//line views/base.qtpl:31
func (p *BasePage) Title() string {
//line views/base.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line views/base.qtpl:31
	p.WriteTitle(qb422016)
//line views/base.qtpl:31
	qs422016 := string(qb422016.B)
//line views/base.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line views/base.qtpl:31
	return qs422016
//line views/base.qtpl:31
}

//line views/base.qtpl:32
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line views/base.qtpl:32
	qw422016.N().S(`This is a base body`)
//line views/base.qtpl:32
}

//line views/base.qtpl:32
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line views/base.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/base.qtpl:32
	p.StreamBody(qw422016)
//line views/base.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line views/base.qtpl:32
}

//line views/base.qtpl:32
func (p *BasePage) Body() string {
//line views/base.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line views/base.qtpl:32
	p.WriteBody(qb422016)
//line views/base.qtpl:32
	qs422016 := string(qb422016.B)
//line views/base.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line views/base.qtpl:32
	return qs422016
//line views/base.qtpl:32
}
