// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package todos

import (
	"database/sql"
)

type Todo struct {
	ID          int64
	Status      sql.NullBool
	Description string
}
