// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"time"
)

type Note struct {
	ID        int64
	Content   string
	UserID    int64
	IsPublic  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	FirstName sql.NullString
	LastName  sql.NullString
	Password  string
	Email     string
}
